import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to adhoc
        </h1>

        <p className={styles.description}>
        the story generator for kids
        </p>

      </main>

      <footer className={styles.footer}>
        &copy; 2022 Tony Wieczorek
      </footer>
    </div>
  )
}

export default Home
